# Generated by Django 5.0.6 on 2024-05-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalappLoginmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField(default=False, max_length=100)),
                ('loginuname', models.CharField(max_length=100, null=True)),
                ('userrole', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100, null=True)),
                ('line', models.CharField(default='noline', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LocalseverHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('savedid', models.CharField(max_length=100)),
                ('operationdone', models.CharField(max_length=100)),
                ('donebyuser', models.CharField(max_length=100)),
                ('donebyuserrole', models.CharField(max_length=100)),
                ('donedatetime', models.DateTimeField(max_length=100)),
                ('description', models.CharField(default='True', max_length=300)),
                ('donebyemployeeid', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printerdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('printer_id', models.IntegerField(default=False, max_length=100)),
                ('processordernumber', models.CharField(default=False, max_length=100, unique=True)),
                ('expiration_date', models.DateField(null=True)),
                ('lot', models.CharField(max_length=100, null=True, unique=True)),
                ('gtin', models.CharField(max_length=100, null=True, unique=True)),
                ('numbers', models.JSONField(blank=True, null=True)),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('hrf', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('ip_address', models.CharField(max_length=100, null=True)),
                ('printed_numbers', models.JSONField(null=True)),
                ('balanced_serialnumbers', models.JSONField(null=True)),
                ('responsefield', models.BooleanField(default=False)),
                ('preparebuttonresponse', models.BooleanField(default=False)),
                ('stopbtnresponse', models.BooleanField(default=False)),
                ('start_pause_btnresponse', models.BooleanField(default=False)),
                ('pause_stop_btnresponse', models.BooleanField(default=False)),
                ('return_slno_btn_response', models.BooleanField(default=False)),
                ('batchstopmessage', models.BooleanField(default=False)),
                ('label_response', models.CharField(max_length=100, null=True)),
                ('child_numbers', models.JSONField(blank=True, null=True)),
                ('scannergradefield', models.JSONField(blank=True, null=True)),
                ('loadpause', models.BooleanField(default=True)),
                ('Rejectednumbers', models.JSONField(blank=True, null=True)),
                ('acceptednumbers', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scannerdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gtin', models.CharField(max_length=100, null=True)),
                ('numbers', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(max_length=100, null=True)),
                ('grade', models.JSONField(blank=True, default='[{"serialnumber":"grade"}]')),
                ('status', models.CharField(max_length=100, null=True)),
                ('serialnumber', models.CharField(max_length=100, null=True)),
                ('gradevalue', models.CharField(max_length=100, null=True)),
                ('lot', models.CharField(max_length=100, null=True)),
                ('finalstatus', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
