# Generated by Django 5.0.6 on 2024-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0002_alter_printerdata_gtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdata',
            name='printerstatefield',
            field=models.BooleanField(default=False),
        ),
    ]
