# Generated by Django 5.0.6 on 2024-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0004_remove_printerdata_printerstatefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdata',
            name='printerstatefield',
            field=models.BooleanField(default=False),
        ),
    ]
