# Generated by Django 5.0.6 on 2024-05-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0005_printerdata_printerstatefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerdata',
            name='printerstatefield',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
