# Generated by Django 5.0.6 on 2024-06-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0008_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Localapp_Register',
        ),
    ]
