# Generated by Django 5.0.6 on 2024-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0009_rename_register_localapp_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local_UserrolePermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('admin', models.JSONField(default={'CREATE': 'Checked', 'DELETE': 'Checked', 'READ': 'Checked', 'UPDATE': 'Checked'})),
                ('operator', models.JSONField(default={'CREATE': 'Checked', 'DELETE': 'Checked', 'READ': 'Checked', 'UPDATE': 'Checked'})),
                ('masterdata', models.JSONField(default={'CREATE': 'Checked', 'DELETE': 'Checked', 'READ': 'Checked', 'UPDATE': 'Checked'})),
                ('supervisor', models.JSONField(default={'CREATE': 'Checked', 'DELETE': 'Checked', 'READ': 'Checked', 'UPDATE': 'Checked'})),
            ],
        ),
    ]
