# Generated by Django 5.0.6 on 2024-06-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0010_local_userrolepermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdata',
            name='jobstatus',
            field=models.CharField(default='Not Added', max_length=100),
        ),
    ]
