# Generated by Django 5.0.6 on 2024-06-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0011_printerdata_jobstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerdata',
            name='jobstatus',
        ),
    ]
