# Generated by Django 5.0.6 on 2024-06-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0013_printerdata_start_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdata',
            name='current_sn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
