# Generated by Django 5.0.6 on 2024-07-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0014_printerdata_current_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerdata',
            name='batchstopmessage',
        ),
        migrations.RemoveField(
            model_name='printerdata',
            name='current_sn',
        ),
        migrations.RemoveField(
            model_name='printerdata',
            name='label_response',
        ),
        migrations.RemoveField(
            model_name='printerdata',
            name='loadpause',
        ),
        migrations.RemoveField(
            model_name='printerdata',
            name='pause_stop_btnresponse',
        ),
        migrations.RemoveField(
            model_name='printerdata',
            name='preparebuttonresponse',
        ),
        migrations.RemoveField(
            model_name='printerdata',
            name='responsefield',
        ),
        migrations.RemoveField(
            model_name='printerdata',
            name='return_slno_btn_response',
        ),
        migrations.RemoveField(
            model_name='printerdata',
            name='start_button',
        ),
        migrations.RemoveField(
            model_name='printerdata',
            name='start_pause_btnresponse',
        ),
        migrations.RemoveField(
            model_name='printerdata',
            name='stopbtnresponse',
        ),
    ]
