# Generated by Django 5.0.6 on 2024-07-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0015_remove_printerdata_batchstopmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdata',
            name='load_button_resp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printerdata',
            name='return_button_resp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printerdata',
            name='start_button_resp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printerdata',
            name='stop_button_resp',
            field=models.BooleanField(default=False),
        ),
    ]
