# Generated by Django 5.0.6 on 2024-07-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0016_printerdata_load_button_resp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdata',
            name='server_button_resp',
            field=models.BooleanField(default=False),
        ),
    ]
