# Generated by Django 3.2.5 on 2024-07-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0017_printerdata_server_button_resp'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdata',
            name='serverstatus',
            field=models.CharField(default='Not Updated', max_length=100),
        ),
    ]
