# Generated by Django 3.2.5 on 2024-07-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0020_auto_20240709_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inproperly_Closed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('close_update', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
