# Generated by Django 3.2.5 on 2024-08-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0021_inproperly_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdata',
            name='trigger_flag',
            field=models.BooleanField(default=False),
        ),
    ]
