# Generated by Django 5.0.6 on 2024-06-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Loginmodel',
        ),
        migrations.DeleteModel(
            name='Loginmodel2',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='UserAuditHistoryOnly',
        ),
        migrations.DeleteModel(
            name='UserrolePermissions',
        ),
    ]
