# Generated by Django 5.0.6 on 2024-07-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdataapp', '0002_remove_serverprinterdata_batchstopmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprinterdata',
            name='server_button_resp',
            field=models.BooleanField(default=False),
        ),
    ]
