# Generated by Django 5.0.6 on 2024-07-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdataapp', '0003_serverprinterdata_server_button_resp'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprinterdata',
            name='load_button_resp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverprinterdata',
            name='return_button_resp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverprinterdata',
            name='start_button_resp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverprinterdata',
            name='stop_button_resp',
            field=models.BooleanField(default=False),
        ),
    ]
