# Generated by Django 3.2.5 on 2024-07-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverdataapp', '0005_serverprinterdata_serverstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverprinterdata',
            name='serverstatus',
        ),
    ]
