# Generated by Django 3.2.5 on 2024-07-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdataapp', '0006_remove_serverprinterdata_serverstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprinterdata',
            name='production_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serverprinterdata',
            name='production_time',
            field=models.TimeField(null=True),
        ),
    ]
