# Generated by Django 3.2.5 on 2024-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdataapp', '0007_auto_20240709_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupScannerdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gtin', models.CharField(max_length=100, null=True)),
                ('numbers', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(max_length=100, null=True)),
                ('grade', models.JSONField(blank=True, default='[{"serialnumber":"grade"}]')),
                ('status', models.CharField(max_length=100, null=True)),
                ('serialnumber', models.CharField(max_length=100, null=True)),
                ('gradevalue', models.CharField(max_length=100, null=True)),
                ('lot', models.CharField(max_length=100, null=True)),
                ('finalstatus', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
