# Generated by Django 3.2.5 on 2024-07-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdataapp', '0008_backupscannerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupscannerdata',
            name='send_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='backupscannerdata',
            name='send_time',
            field=models.TimeField(null=True),
        ),
    ]
