# Generated by Django 3.2.5 on 2024-07-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdataapp', '0009_auto_20240713_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupscannerdata',
            name='update_date',
            field=models.DateField(null=True),
        ),
    ]
