# Generated by Django 3.2.5 on 2024-08-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdataapp', '0010_backupscannerdata_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('savedid', models.CharField(max_length=100)),
                ('operationdone', models.CharField(max_length=100)),
                ('donebyuser', models.CharField(max_length=100)),
                ('donebyuserrole', models.CharField(max_length=100)),
                ('donedatetime', models.DateTimeField(max_length=100)),
                ('description', models.CharField(default='True', max_length=300)),
                ('donebyemployeeid', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
